### ISSUE TITLE
[Bug] Ignores the option

### ISSUE THREAD

**Issue by MrBeat93** [TheRedBrain/combatroll-extension#2]
I'm able to roll when the "rolling_requires_stamina" is set to "true"

https://github.com/user-attachments/assets/3636ea79-529f-40f9-b791-44bcaa39c5f0

Also, make a option so the minimun stamina required, is the same as the cost
Otherwise the stamina goes to negative value which makes the regen take longer to reach 1

**Comment by TheRedBrain** [comment]
Hi!

If I see this correctly, you have the stamina cost for rolling set to 2.
You can still roll while having only 1 stamina and your stamina then goes to -1.

That is working as intended. It rewards managing your stamina, so your stamina doesn't drop below 0. The longer regeneration when stamina is below 0 is the punishment for bad stamina management. This gameplay design is used in many popular games.

However I can still add an option for the "rolling_requires_stamina" check to check for the actual cost, instead of stamina > 0.
Would that solve your problem?

**Comment by MrBeat93** [comment]
Hello

Yeah, I think that new option would be great!

**Comment by TheRedBrain** [comment]
added to my todo list :)

**Comment by TheRedBrain** [comment]
Added the "rolling_requires_stamina_cost" option in versions 1.2.0 for 1.20.1 and 2.1.0 for 1.21.1
